name: Coverage
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Generate Report
        run: ./gradlew library:koverPrintCoverage

      - name: Extract Coverage
        id: extract_coverage
        run: |
          PERCENTAGE=$(grep "line coverage" library/build/kover/coverage.txt | grep -oP '\d+(?=%)')
          PERCENTAGE=${PERCENTAGE:-0}
          
          echo "percent=$PERCENTAGE" >> $GITHUB_OUTPUT
          
          # Logic to determine color based on percentage
          if [ "$PERCENTAGE" -ge 90 ]; then
            echo "color=green" >> $GITHUB_OUTPUT
          elif [ "$PERCENTAGE" -ge 75 ]; then
            echo "color=yellow" >> $GITHUB_OUTPUT
          else
            echo "color=red" >> $GITHUB_OUTPUT
          fi

      - name: Update Badge Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 985b3f7fb1939b630ec7c6a06e77434b
          filename: coverage.json
          label: Coverage
          message: ${{ steps.extract_coverage.outputs.percent }}%
          color: ${{ steps.extract_coverage.outputs.color }}
